### ISSUE TITLE
Perow Creek 197653

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#103]

**Comment by Mateo9569** [comment]
This would need to be changed in fpr because wetted width is part of the `fpr_my_habitat_paragraph` function. I could just put the words in manually for now as a quick fix.

**Comment by NewGraphEnvironment** [comment]
A print of `fpr_my_habitat_paragraph ` to the console will show that it is a function made of several other functions put together. Those smaller functions can be called (or excluded) individually in cases like this.
