### ISSUE TITLE
Stream Characteristics Upstream of 195944-Can you please characterize whether the 65 cm rock drop is likely to be passable/partially passable by adult salmon/steelhead?

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#104]

**Comment by Mateo9569** [comment]
@NewGraphEnvironment am I correct in saying that this is passable for adult salmonids but could be a barrier to younger fish? What's your professional opinion.

**Comment by NewGraphEnvironment** [comment]
When we have obstacles like this noted in our field notes, it is often best to include a picture of it in the report with a little bit of text about it in the caption (ie. size of drop and it’s distance upstream from the crossing). I will have to have a look at the photo to confirm but that size of a drop is likely easily passible to adult steelhead and coho, but dependent on flow conditions is likely an issue for upstream migration for all life stages of resident fish as well as non-adult life stages of ST and CO. Can you add in the photo (perhaps swap a different one out), draft the text and then I can address and close the issue after a pull?

**Comment by Mateo9569** [comment]
Closed via https://github.com/Mateo9569/fish_passage_bulkley_2022_reporting/commit/d1739a24ab84d6e992c4ae89e70e65c94e7c98ff
