### ISSUE TITLE
When I try to add portrait photo of waterfall it automatically rotates to landscape when report is built

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#106]
I'm thinking this might be due to something in the `grid.raster` package function called in the code chunk.

**Comment by NewGraphEnvironment** [comment]
thinking that more likely the photo is rotated by the viewer due to a metadata tag of somesort but the underlying photo is actually landscape.  you could try the `fpr::fpr_photo_flip` function and set the `rotate` param accordingly.  It burns another photo to the file with `rotated_` appended to the front of the filename so you would point to that photo to test

**Comment by Mateo9569** [comment]
I can't get the `fpr_photo_flip` to work. The function doesn't seem to be reading the correct file.  I don't understand why the `data/photos/198116` part of the file path is being repeated twice (see below). As you can see on line 292 I'm pulling the waterfall picture by the `_u6_` file name portion which I appended. And `my_site` is correctly defined in my environment.

![image](https://user-images.githubusercontent.com/99455166/215890015-9f2d51c8-e860-40b1-88f2-8d8c9e9dd695.png)

**Comment by NewGraphEnvironment** [comment]
hmm.  looks like I've changed the helper function `fpr::fpr_photo_pull_by_str` at some point and turned off the last call to `basename`.  I will add a switch to that one so that we can still use it.  Thanks for the heads up

```
fpr::fpr_photo_pull_by_str
function(site = my_site, str_to_pull = 'barrel'){
  list.files(path = paste0(getwd(), '/data/photos/', site), full.names = T) %>%
    stringr::str_subset(., str_to_pull) %>%
    gsub(paste0(getwd(), '/'), '', .)
  # basename()
}
<bytecode: 0x11583ba18>
<environment: namespace:fpr>
```

**Comment by NewGraphEnvironment** [comment]
actually, its probably easier to just fix the `fpr::fpr_photo_flip` function.  I will make an issue and close but in the meantime you could hack it by running the following in your console then useing it..

```
photo_flip <- function(site_id = my_site, rotate = 180, str_to_pull = 'barrel'){
  photo <- fpr_photo_pull_by_str(site = site_id, str_to_pull = str_to_pull)
  magick::image_read(photo) %>%
    magick::image_rotate(rotate) %>%
    magick::image_write(paste0('data/photos/', site_id, '/rotated_', basename(photo)))
  
}
```
