### ISSUE TITLE
Insert Waterfall map link manually 

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#107]
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/9282af3b6fdf899e3b5be398310b0928441cefe6/0800-appendix-198116-waterfall.Rmd#L68

Just caught this as I was looking something up in this memo. When the report is built the last sentence just reads "A map of the watershed is provided in map attachment ". You could just delete that sentence, because there's already a map of the watershed provided in Figure 5.19.

**Comment by NewGraphEnvironment** [comment]
let's handbomb the link into there.  The pdf maps provide a lot of context and are georeferenced .  

We could consider looking at the layer name we have used before when giving Simon line data in `bcfishpass_mapping.gpkg `to show the correct streamline orientation when the freshwater atlas is not correct. He marks up the maps with priority rankings, watershed areas, fish observations, obstacles and field tracks

**Comment by Mateo9569** [comment]
Good point, I rescind that suggestion. Maps always tell a better story, better to have one in there. You want me to do it?

**Comment by NewGraphEnvironment** [comment]
all 800? ha - https://hillcrestgeo.ca/outgoing/fishpassage/projects/

**Comment by NewGraphEnvironment** [comment]
As per the `fpr::fpr_my_mapsheet` function, we put the name of the mapsheet in link so that it provides more information.
