### ISSUE TITLE
Missing photos for bullkey bridge assessment adjacent to the Zymoetz watershed group

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#11]
One of the bridges that she looked at on the way back from the zymoetz is just past the boundary, in the bulkley. I can't seem to find the photos for it. Looking in Q I can see that she added photos in mergin but I can't find them in the one drive skeena folder.

**Comment by NewGraphEnvironment** [comment]
Did we happen to try looking in V226 yet (immediately after when the photos may have been uploaded)? Guessing dates are after 107 and V106 but those are also TP uploads....

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/46538103/204305276-1f6f1a77-1a07-4207-95ce-7de2dc6b8c15.png">

**Comment by NewGraphEnvironment** [comment]
this bridge needs to be added to a pscis submission spreadsheet.

**Comment by Mateo9569** [comment]
I found the photos. I downloaded version 226 and they were in the photos folder. I did add the bridge to the submission sheet, it's in the reassessment sheet.
