### ISSUE TITLE
match surveyed crossings to bcfishpass modelled crossings

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#110]
use the `match_this` object from [here](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/9282af3b6fdf899e3b5be398310b0928441cefe6/scripts/02_reporting/0160-load-bcfishpass-data.R#L193)  and mod to your initials for a big headstart to a spreadsheet that can be appended to https://github.com/smnorris/bcfishpass/blob/main/data/pscis_modelledcrossings_streams_xref.csv.  Give me a heads up when your fork is ready and I can have a quick peak before you PR.  Don't forget to remove the duplicates as per https://github.com/smnorris/PSCIS_datafixes/issues/13

best to clone my bcfishpass repo and then you can keep up with our specific tweaks. Should be able to set simons repo as another upstream (different name) and still do PRs as long as your fork has all his latest changes pulled in before you make the branch. Might be a few different ways to do it though

**Comment by Mateo9569** [comment]
I matched the crossings [here](https://github.com/NewGraphEnvironment/bcfishpass/compare/main...Mateo9569:bcfishpass:modelled_xref). I also added one from zymoetz and the one from parsnip you mentioned in [this issue](https://github.com/NewGraphEnvironment/fish_passage_peace_2022_reporting/issues/17). Haven't done a PR yet so you can take a look.

**Comment by Mateo9569** [comment]
@NewGraphEnvironment did you ever take a look at the crossings I added, referenced in the commit I mentioned above? Before I blow up my repo I just wanted to know if I should PR those changes, or transfer them over to a new fork in my account.

**Comment by NewGraphEnvironment** [comment]
OMG - I spent well over an hour writing recommendations for better notes for each line item and detailing how to deal with those duplicates (do it later due to issue) then there was an issue with bcfishpass that I got in touch with simon for. then I opened a million windows and closed the one with all my work before sending. Basically - you may as well use a fork of Simon's but please redo the comments for all the crossings besides the dupes so it is really clear what we are doing and why (ex. Stock creek - "actual crossing is highway. Was tied to road line but actual road does not exist" - for Perow - "coordinates for incorrect modelled crossing was used in pscis submission - crossing is on perow Creek", etc.). for the dupes there is an issue with simons latest build so let's do those after. when we do it we shoudl tie the dupe that we are keeping to the modelled crossing id vs exnaying the one to be discarded (since it will be discarded in PSICS ecentually). Please let me review the changes before making a PR to Simon.

**Comment by NewGraphEnvironment** [comment]
Also - because `bcbarriers` is wacked out right now I need to get you going on our development server so you can see a proper `bcfishpass.crossings` layer.  You will need that to deal with the dupes as that is where I noticed the wackout.  I am going to try to focus on moti in the morning but will see if I can get you set up in pg on the dev server tomorrow afternoon

**Comment by NewGraphEnvironment** [comment]
I guess if the information about the join is already in our PSCIS submission we perhaps don’t need to repeat it. I’m thinking about perow creek being in the stream name and the highway being in the road name type of thing. Maybe those examples are actually fine. Too bad I gorbed on the detailed review I did earlier. Ga

**Comment by Mateo9569** [comment]
Ok so just to clarify, I'm leaving the duplicates out of the csv for now? I can redo the comments for the other ones and add that one from skeena 2021 we talked about yesterday. I'll fork Simon's with the latest and push to a new branch and leave a link to it here so you can check it out.
