### ISSUE TITLE
submit Causqua Creek to province

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#118]
Looks like 1802374 did not get into Mergin.  Will need to put it in its own spreadsheet for provincial submission. The amount of work that will be required to get this into the report is intense and not something we can take on.  Dissapointing but a reality and not that big a deal since it is a ford. Once submitted to PSCIS the models will see it which is good.

![image5](https://user-images.githubusercontent.com/46538103/222208197-154f0526-65a1-4f6e-b246-800e45e39f4b.jpeg)
![image4](https://user-images.githubusercontent.com/46538103/222208202-c2840580-2d49-4f54-8a05-6ccf4ef5fba6.jpeg)
![image3](https://user-images.githubusercontent.com/46538103/222208206-adddd3ea-574d-4062-b40c-a20ad1e308f7.png)
![image2](https://user-images.githubusercontent.com/46538103/222208211-30f63f36-b208-49ab-8b8d-492572de2179.png)
![image1](https://user-images.githubusercontent.com/46538103/222208214-b4f7da78-cfaa-4311-9502-f874c480c4b2.png)
![image0](https://user-images.githubusercontent.com/46538103/222208219-c122c9b5-be09-46f0-aaa3-7b4f1ea54808.png)

**Comment by Mateo9569** [comment]
I've lined this up for submission. Before I submit though I just want to double check with you that you haven't submitted already and forgot to close this issue?

**Comment by NewGraphEnvironment** [comment]
good to go.  I haven't touched it.

**Comment by Mateo9569** [comment]
I'm assuming all the info on the cover page in the pscis submission template is the same from the bulkley 2022 one? And for the 6 required photos I just used the ones you posted above in the issue and then made copies so I had 6. Instead of using the blank ones that have no image available on them.

**Comment by NewGraphEnvironment** [comment]
We only need 5 photos for submission (road is our own and if we don't have it no need to hack).  Generally I would use the blanks if there are lots missing and because we aren't putting the amalgamated photo in the report but you can leave it as is.  I would change the things below for accuracy and so it doesn't bounce back as a duplicate (might be fine but not sure how PSCIS would deal with multiple submissions with the same Project Number/name).  Likely to choke and eat more of our time I would guess


project number: bulkley_2022_Phase1b
project name: Bulkley River Fish Passage Restoration Planning 2022 - Phase 1b
Project Budget: 250

**Comment by Mateo9569** [comment]
Understood. I'll change the project info then submit, and close this issue once it's done.

**Comment by Mateo9569** [comment]
Done, and uploaded submission folder to onedrive under projects/PSCIS/Phase1_submissions/
