### ISSUE TITLE
Update the `user_modelled_crossing_fixes.csv` bcfishpass file with all we know

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#119]
the modelled crossing on Stock Creek right by the highway (need to figure out the modelled xing id) needs to go in here as it does not exist

https://github.com/smnorris/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv

**Comment by Mateo9569** [comment]
This was dealt with via commit linked [here](https://github.com/smnorris/bcfishpass/pull/331/commits/7615f60b51f8d3fff3d53bca589487b31da0c87f) that was merged into Simons repo
