### ISSUE TITLE
1:50,000 stream layer has Watson Creek and Ailport Creek names mixed up

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#124]
The gazetted names are switched in this layer. Watson Creek is where Ailport Creek should be and vice versa. Wondering if the watershed codes are also mixed up or if they are correct?

**Comment by NewGraphEnvironment** [comment]
Good question. Names are mixed up but we can document watershed code as is.
