### ISSUE TITLE
Remove thompson creek assessment from reporting objects

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#133]
Site 198066 was revisited in 2022, but it is now part of the skeena 2021 report and not this one. I can leave it in the habitat confirmation and priorities sheet but take it out everywhere else. The tracks and photos still show up on the interactive map in the results section. It is also in the `hab_site_priorities` mapping object, and in table 4.8 of results.

**Comment by NewGraphEnvironment** [comment]
lets put a note in the hab priorities comments that lets the reader know where to look for the memo.  It will show in table 4.8.  This issue will need to be reopened after I merge

**Comment by Mateo9569** [comment]
Sure I can put a note in the priorities sheet. I did filter the site out of table 4.8. You want me to add it back in?

**Comment by NewGraphEnvironment** [comment]
nah - if it's not there- it is fine as is
