### ISSUE TITLE
2022091003 from Waterfall Creek at 9th ave has a bunch of missing data in input spreadsheet

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#19]
@Mateo9569 is there a paper card for this?  If so - can you upload a photo of it here?

**Comment by Mateo9569** [comment]
![20221130_133351](https://user-images.githubusercontent.com/99455166/204914118-1c52f514-3b8f-4c70-996a-f5174b3a0f8f.jpg)
That has all the info. I misplaced the card into the wrong folder and was just going off the mergin data before (which had some missing data). I got the card now.
