### ISSUE TITLE
2022091002 - Waterfall Creek - no culvert slope data

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#20]
@Mateo9569 -  Is there a culvert slope written on the card?

**Comment by Mateo9569** [comment]
Ya it's says 2.5% on the site card. Not sure how I missed that the first time. Do you want to input that or should I?

**Comment by NewGraphEnvironment** [comment]
got it
