### ISSUE TITLE
stop tracking the bcfishpass.splite changes in repo unless changes to underlying tables actually happens and eventually serve db from elsewhere

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#24]
Everytime we touch our sqlite database it logs in git as a change. Not sure if it is because it is binary or because of metadata updates but regardless it will balloon our repo. 

For now lets stop tracking the `bcfishpass.sqlite `changes in repo unless changes to underlying tables actually happen by running the script below

` git update-index --assume-unchanged data/bcfishpass.sqlite`. When changes actually occur we use `git update-index --no-assume-unchanged data/bcfishpass.sqlite` to log a commit

@Mateo9569 please run the `assume-unchanged` command in your terminal.  It will then stop showing up in your Git window on Rstudio everytime you run the `scripts/tables.R` script.  Then can you please make a wee note here to confirm it worked?  

Once/if we move the whole sqlite database to a remote spot we can all access we can close this issue.

**Comment by Mateo9569** [comment]
I ran the git unchanged command and then ran the tables script. The script ran fine. But then I got these files showing up in my git window.

![image](https://user-images.githubusercontent.com/99455166/207946001-f700ce00-baff-4292-9a61-1f55daf101d2.png)

**Comment by NewGraphEnvironment** [comment]
naturally.  Those are from `fpr::fpr_import_hab_con()` .  Thats how we back up our versions of the fish submission template in a format that is easy to track.  We will have a similiar system for the pscis imports in place soon too. Those will now only show in git once they actually change. There is a switch in the function to turn it and off ;)

Unrelated to the sqlite.  If it doesn't show the sqlite in the git window after you accessed the database (like through the `tables.R` script  it worked! 

Try the same thing with `git update-index --assume-unchanged data/habitat_confirmations.xls` .  then open the file and close it.  It shouldn't show in the git window even though git doesn't know it hasn't changed.  After the test  unignore it again with a `git update-index --no-assume-unchanged data/habitat_confirmations.xls` until we get a stable version that we are unlikely to need to change often.....

Moves like this help us get around the ramifications of our bad practice of storing binary files on git!

**Comment by NewGraphEnvironment** [comment]
```
airvine at Allans-MacBook-Pro in ~/Projects/repo/fish_passage_skeena_2022_reporting on main [!?]
$ git update-index --no-assume-unchanged data/bcfishpass.sqlite
fatal: Unable to mark file data/bcfishpass.sqlite
```
