### ISSUE TITLE
`fpr_import_pscis_all` creates `pscis_list` as one object vs list of 3 objects which causes arrange to fail

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#27]
I ran into a snag on the repo. Hopefully the screenshot is big enough. The issue seems to be coming from the arrange function in the lines below, apparently because there are NAs in the `pscis_phase2` sheet?
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/7796daad84ee861fd3449ae81cc401c2bdd7566e/scripts/tables.R#L15
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/7796daad84ee861fd3449ae81cc401c2bdd7566e/scripts/tables.R#L16

But I added the newly created pscis ids from the bc data catalogue to the phase_2 spreadsheet, saved and re ran the script and I'm still getting the same error.

![image](https://user-images.githubusercontent.com/99455166/208213284-5251d99a-4d25-4645-8d59-8e7c145cb4ef.png)

**Comment by NewGraphEnvironment** [comment]
see https://github.com/NewGraphEnvironment/fpr/issues/9

fixed it but forgot to commit.  Updated `fpr` , tested and push release tag to today and bumped development version. 

Should be just a fetch and pull on `fpr` then a rebuild install locally to get it working
