### ISSUE TITLE
Use photo of card if no road photo available

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#32]
`Appendix - Phase 1 Fish Passage Assessment Data and Photos` now has a build

the "road" photo does not need to have a road in it if there is no road. When there is no road over the actual crossing the road photo is a photo FROM the road that shows where the mapped road would be and the site id on the card in the corner.  We could even go so far as to have just a picture of the site number if that is all we have.  It is better than the nasty white missing photo....

@Mateo9569 can you take this on swapping out no_photo for road when we can and rerunning the amalgamate photo script?  Can you update the readmes so they aligns with the `fpr_photo_amalgamate` script for this to make it easy to find in the future?

**Comment by Mateo9569** [comment]
So a photo of the site card is fine? Most of the sites that are fords don't have road photos, just photos of the site cards in the corner.

**Comment by NewGraphEnvironment** [comment]
usually we walked in on what was or is a road.  like mentioned above - it is the perspective from the road and does not need to be a road per se.  Plus - even just a card has some info as it confirms that the IDs match (usually anyway) and that is better than a big ugly white no-photo photo
