### ISSUE TITLE
`xref_pscis_my_crossing_modelled` missing `external_crossing_reference` - sqlite changed locally but not in repo

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#34]
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/eef95d73601db759e79e0dd0ae8adbd740f2d9ce/scripts/tables.R#L78-L81

My error comes from these lines. Because it's trying to do a left join but there is no column called "external_crossing_reference" in the `xref_pscis_my_crossing_modelled` table. Is my bcfishpass not up to date or something? Here's a screenshot of the error message in R.

![image](https://user-images.githubusercontent.com/99455166/209247096-6d7036bb-da4b-468a-8814-388b0af223a5.png)

**Comment by NewGraphEnvironment** [comment]
Aha! its because I have updated the sqlite database but did not commit it since it is assumed unchanged as per https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/issues/24 . will close with push
