### ISSUE TITLE
Rstudio inserting %60%20 into formulas that link and now Site maps aren't showing up

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#38]
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/08c19fcd192dcc1752a45cb4bb64fba6f4e1cb0f/0800-appendix-197653-perow.Rmd#L72

When you reviewed perow and watson you changed the above line and now I can't get the maps to show. Before this the mapsheet function was just: `r fpr::fpr_my_mapsheet()`, without the numbers and percent signs. Are the numbers 20 and 60 just adjusting the size of the map view? When I click on the link in the built report it sends me to an error page that says file could not be accessed. 

I can get the map to show up fine for Valee Creek: https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/08c19fcd192dcc1752a45cb4bb64fba6f4e1cb0f/0800-appendix-57793-valee.Rmd#L54

**Comment by NewGraphEnvironment** [comment]
Nothing I did manually but I have seen it happen automatically before. 

Not sure why Rstudio is inserting %60%20 into formulas that link.  

Seems similar to how it is replacing {-} with {.unnumbered} on our headers.

May be related to viewer mode in Rstudio? Would be good to search the Rstudio GitHub repo issues to see if we can find out how to remedy the situations. Googling it could help too.

**Comment by Mateo9569** [comment]
Ok I'll look into it. Just wanted to check with you first if it was something you did on purpose.

**Comment by NewGraphEnvironment** [comment]
Nah a it’s weird. Was happening last spring too. I forgot about it. Odd.  could be worth looking at `knitr`  issues or any other package involved in that function (can’t remember what’s in there).

**Comment by NewGraphEnvironment** [comment]
known issue in Rstudio not yet with solution

https://github.com/rstudio/rstudio/issues/12368
