### ISSUE TITLE
unable to connect to the postgres database

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#40]
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/08c19fcd192dcc1752a45cb4bb64fba6f4e1cb0f/scripts/outgoing-mapping.R#L32-L40

I'm having an issue connecting to the database in the mapping script. The error message just says: "Error: FATAL:  password authentication failed for user "postgres"". I'm assuming it is because my environmental variables aren't set correctly? I remember you posting a note about this somewhere but I couldn't locate it.

**Comment by NewGraphEnvironment** [comment]
1.   i think you only need to access a database if you wanted to grab watershed group shapes.  Pretty sure the rest of that script doesn't need a pg db connection...
2. those are settings for a local database which you don't have.  you will need to alter the script to connect to the remote database if that is what you want to do

**Comment by Mateo9569** [comment]
Ya I need it to get the study area watersheds. Which is also needed in the web map in the results section. How do I connect to the remote db?

**Comment by NewGraphEnvironment** [comment]
call the connection params for `bcbarriers`

**Comment by NewGraphEnvironment** [comment]
make sure to alter the query so the study area is only `BULK`

**Comment by Mateo9569** [comment]
Got it working.
