### ISSUE TITLE
duplicates entered to pscis for all phase 1 sites!

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#41]
probably need to do it here

https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/b67cbc3e4e81d68790975ecb0d42c8f7a5e6c655/scripts/02_reporting/0160-load-bcfishpass-data.R#L147

**Comment by Mateo9569** [comment]
Do I run from line 147 down to the end of the script? And this is to link the pscis ids for the two sites in the waterfall memo that are still listed as my_crossing_reference ids, correct? I was wondering about that, I assumed they would have to be changed.

**Comment by NewGraphEnvironment** [comment]
hmm. I think so - but I am not sure why it didn't work the first time though.... will be tweaks as it needs to be erased from the sqlite and reburned. not everything to the end of the script should need to be run 9just https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/b67cbc3e4e81d68790975ecb0d42c8f7a5e6c655/scripts/02_reporting/0160-load-bcfishpass-data.R#L141 and then cherry picking opening the sqlite, deleting the old xref (if the new one is differnt) and burning in the new one.

Might be something weird going on though as not sure why it aint there already. It should be a simple join of the my_crossing_id and the external_crossing_reference..... Worth a try

**Comment by Mateo9569** [comment]
Looks like they are in the sqlite already. I didn't touch anything in the `0160-load-bcfishpass-data.R` script. But when I look at the join of the my_crossing_id and the external_crossing_reference, the Waterfall sites all have two different stream crossing ids assigned to them. Why did that happen? Is that because those sites show up in the phase 1 and the phase 2 spreadsheet? Which ID do I use?
![image](https://user-images.githubusercontent.com/99455166/210457511-03c1b1c5-f1fb-40ef-b76c-4cb25c501bcb.png)

**Comment by NewGraphEnvironment** [comment]
ah crap. looks to me like the data went into the system twice. Our first submission must have actually cleared into PSCIS after the hang up - without letting us know.  l'll loop in @smnorris to see if there is a PR we can do to document and or resolve the issue somehow.  

For our reporting - for now - let's axe the first ID (filter out everything with a stream_crossing_id < 198109 and resave to the sqlite

**Comment by smnorris** [comment]
Yes, I noticed the duplication.  Can you please file an issue here? https://github.com/smnorris/PSCIS_datafixes/issues

All that is needed are the `stream_crossing_id` values of duplicated records, noting which records you'd like to retain in PSCIS, and which ones to delete.

At some point I'll make and submit a data fix to PSCIS but for now I can just filter out these duplicates when bringing the data into `bcfishpass`. I don't think there is an existing mechanism for this but it is an easy add.

**Comment by NewGraphEnvironment** [comment]
a two column csv burned out from the tables script (or wherever) with the lower number duplicate included should be fine.  Read the readme at simon's site

**Comment by NewGraphEnvironment** [comment]
@Mateo9569 - please file an issue here? https://github.com/smnorris/PSCIS_datafixes/issues

Also do an issue for Perow mismatch as well
