### ISSUE TITLE
`fpr_table_cv_summary_memo` fails.  waterfall culvert summaries break build as they are not in the `pscis_phase2` object and do not have photo directories under PSCIS ID name

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#45]
we can beat this by setting `fpr_table_cv_summary_memo` params to 

`dat = pscis_phase1, site = {my_crossing_reference}, site_photo_id = {my_crossing_reference}, col_filter = my_crossing_reference`

**Comment by Mateo9569** [comment]
I changed the my_crossing_reference for both sites to their psci_ids in the phase2 sheet but forgot to commit the xlsm. Wouldn't that be easier? As opposed to altering the `fpr_table_cv_summary_memo` params

**Comment by NewGraphEnvironment** [comment]
Actually ws able to address by taking care of #41 because then we get a pscis id in the object and a caption that reads correctly
