### ISSUE TITLE
name of tracks geopackage changed

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#46]
best to keep files named same from repo to repo to avoid headache of rewriting scripts.

**Comment by Mateo9569** [comment]
In your commit it says you changed it to `hab_confirmation_tracks` when it was `habitat_confirmation_tracks` in other repos.

**Comment by NewGraphEnvironment** [comment]
right. will revise. thanks!
