### ISSUE TITLE
Perow at hwy 16 is reassessment

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#5]
and should have PSCIS ID

**Comment by Mateo9569** [comment]
Is this crossing not in the system yet? I don't see a pscis id
![image](https://user-images.githubusercontent.com/99455166/200657621-a29b9560-9501-4703-a87c-70c47505a286.png)

**Comment by NewGraphEnvironment** [comment]
looks like the number was written down incorrectly (1800064) and the coordinates were pulled from bcfishpass putting it in the wrong location.  This is from bulkley 2020.  Let's reload it and make a note that it was input incorrectly last time in the comments.  Can you search the `external_crossing_reference` of PSCIS for 1800064 to see the PSCIS ID for this that we can reference in the comments? 

Maybe @smnorris has a smarter solution though.  

![image](https://user-images.githubusercontent.com/46538103/200687619-80b4f195-e351-40a2-8891-cf02a8d178d5.png)

**Comment by smnorris** [comment]
That works fine. Looks like it is PSCIS stream_crossing_id=197657? 

If this is correct, I can force the matching of that PSCIS crossing to 1800067 in bcfishpass.

**Comment by NewGraphEnvironment** [comment]
Flopping around on the best approach for this. Back to thinking a _reassessment_ is actually still the best plan but lets make sure we note in the comments of the reassesment that this crossing was entered in 2020 (or 2021?) with the wrong coordinates and that it actually aligns with bcfishpass modelled crossing id 1800067.

**Comment by NewGraphEnvironment** [comment]
address at same time as #41
