### ISSUE TITLE
need to resize tables in results to eliminate whitespace -  may need to turn `scroll` off too

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#66]
usually can be dealt with by editing `scroll_box_height` in param of `fpr_kable` .  

Not sure if scroll needs to be turned off.  needs a quick build/test

![image](https://user-images.githubusercontent.com/46538103/211373868-03c3207a-09c8-4552-a8ab-a3a64a240538.png)

**Comment by Mateo9569** [comment]
Does this need to be adjusted in the fpr repo? I was testing this yesterday in the bulkley repo and changing params of `fpr_kable` but I didn't notice any changes to the table when I built and inspected

**Comment by NewGraphEnvironment** [comment]
`scroll = F`
