### ISSUE TITLE
Add Coffin Creek dam assessment to main results section

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#70]
similiar to [Bulkley falls ](https://www.newgraphenvironment.com/fish_passage_skeena_2021_reporting/results-and-discussion.htm)and the [dams from Elk 2021 ](https://www.newgraphenvironment.com/fish_passage_elk_2021_reporting/results-and-discussion.html)

**Comment by NewGraphEnvironment** [comment]
be sure to update all links to mapsmadeeasy and turn on uav data chunks before closeing

**Comment by Mateo9569** [comment]
Just going to re open this. What's going on with the dam ID? Why is it like that?

![image](https://user-images.githubusercontent.com/99455166/212144695-54dba281-dec6-42a2-b1da-8ec3a24d54d4.png)

**Comment by NewGraphEnvironment** [comment]
That is the ID.  bcfishpass links to CABD which looks like a CKAN database that has those alphanumeric identifiers.  Took me a while to figure that one out last night
