### ISSUE TITLE
screen sites for incorrect watershed statistics, document, resolve and reference issues

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#71]
sometimes there are things like elevations below sea level.  we can just remove the odd thing if it is weird

**Comment by Mateo9569** [comment]
The only issue with incorrect watershed stats I noticed was the one I referenced in the commit above. The min watershed elevation was way below sea level which is very strange. So I just took out that column in that memo. Hope that was ok.

**Comment by NewGraphEnvironment** [comment]
actually, that min is in the results section summary table too.  will need to do a `case_when` and probably insert a `na_real` if the column type is `numeric`.  Otherwise insert `''`I guess
