### ISSUE TITLE
reference is showing up in book.bib file as a book even though I inputted as report in Zotero

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#75]

**Comment by NewGraphEnvironment** [comment]
related to https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/issues/61

**Comment by Mateo9569** [comment]
Do I have to change this manually in the `book.bib` file to a report item? I've tried restarting R, re inserting the citation but it still doesn't show up as a report. You posted something about this in the zotero slack channel too but I'm not really clear on if you changed it manually or not.

**Comment by NewGraphEnvironment** [comment]
this is a `visual editor` thing and the main reason I switched back to `citr`
