### ISSUE TITLE
should revisit the fish histogram and modify the categories so that the life stages chunk into categories better

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#87]
not a priority but should be done

the breaks in the lengths are the spots to delineate life stages

need to update step 2 of `habitat _confirmation_priorities.xls` as well

**Comment by Mateo9569** [comment]
https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/ea26e1ddd963ec466c27832c039d4918cfa72f34/scripts/01_prep_inputs/0100-extract-inputs.R#L978-L984

So you're saying I should adjust the cutoff lengths in the code section above to match the histogram? Something along the lines of my crude drawing below? 
![image](https://user-images.githubusercontent.com/99455166/212156654-f51b365c-1ee1-4b40-92f8-d7437954571a.png)
