### ISSUE TITLE
Need to mention the downstream crossing on Vallee that the landowner reported wasn't there

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#96]
this site should also be entered into `bcfishpass` [user_modelled_crossing_fixes.csv](https://github.com/smnorris/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv)

**Comment by Mateo9569** [comment]
Should I log an issue in Simons repo? I forked bcfishpass from you and you forked it from Simon so not sure what would happen if I did a commit and PR. Forkception

**Comment by NewGraphEnvironment** [comment]
Its a pull request.  We add lines to the csv and do a PR.  Check out the tutorials in `tutorials/bcfishpass/`. One of them is a direct hit on that

I have a few new rows in a  [user_modelled_crossing_fixes.csv](https://github.com/smnorris/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv) file on one of my forks that can go at the same time. its good for you to see how all of it works and you should start modifyng the csvs as you go from now on.   Lets do the PRs later though.
