### ISSUE TITLE
Vallee Creek updates

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#98]
Need to:

- [x]  reference crossing 1802482 downstream that landowner noted wasn't there and add to https://github.com/smnorris/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv
- [x] Mention the rest of the crossings on the stream (three on mainstem and several modelled on likely very small tributaries)
- [x] need to explicitly state that the upstream data was misplaced and that the stream characteristics listed were estimated by reviewing photos
- [x] manually draw a track based on location the last photos taken by upstream surveyors and add to dataset
- [x] justify the priority ranking as mod because of very small outlet drop and low elevation watershed which likely results in very low flows in typical years however....
- [x] recommend sampling upstream and downstream to provide insight into fish community composition and densities upstream and downstream of the crossing to inform remediation priority
- [x] put link to historic photos when referencing likely low flowshttps://a100.gov.bc.ca/pub/pscismap/imageViewer.do?assessmentId=57833
- [x] 3 of the upstream photos were not from Vallee but from Thompson. Add correct photos.
- [x] update photo metadata with new photos and update outgoing mapping tracks file

**Comment by Mateo9569** [comment]
All tasks addressed here: https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/pull/101. Will close issue upon approval of reviewed changes.

**Comment by Mateo9569** [comment]
Closed with PR https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/pull/101
